# Build Settings
markdown:            kramdown
highlighter:         rouge
permalink:           pretty
plugins:             [jekyll-redirect-from]
safe: false
whitelist:
  - jekyll-redirect-from

title: "Kyle&#39;s World"

# To make _projects & _videos iterable by the for-loops in projects.html and videos.html
collections:
  - projects
  - videos
