# Build Settings
markdown:            kramdown
highlighter:         rouge
permalink:           pretty
plugins:             [jekyll-redirect-from]
safe: false
whitelist:
  - jekyll-redirect-from

sass:
  sass_dir: assets/css
  style: :nested

title: "Kyle&#39;s World"
