# Build Settings
markdown:            kramdown
highlighter:         rouge
permalink:           pretty
plugins:             [jekyll-redirect-from]
safe: false
whitelist:
  - jekyll-redirect-from

sass:
  sass_dir: assets/css
  style: :nested

title: "Kyle&#39;s World"

# To make _videos iterable by the for loop in _pages/videos.html
collections:
  - videos
