# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Projects', folder: 'pages', file: 'projects.html'}
- {name: 'CVEs', folder: 'pages', file: 'cves.html'}
- {name: 'Resume', folder: 'pages', file: 'resume.html'}
- {name: 'CV', folder: 'pages', file: 'cv.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'fa-solid fa-envelope', link: 'mailto:kyle@kyles.world'}
- {icon: 'fa-brands fa-linkedin', link: 'https://www.linkedin.com/in/kyle-timmermans/'}
- {icon: 'fa-brands fa-github', link: 'https://github.com/kyletimmermans'}
- {icon: 'fa-brands fa-twitter', link: 'https://twitter.com/kyletimmermans'}
- {icon: 'fa-brands fa-instagram', link: 'https://instagram.com/kyle_timmermans'}
- {icon: 'fa-brands fa-youtube', link: 'https://www.youtube.com/@TheXeXKyle'}
- {icon: 'fa-brands fa-discord', link: 'https://discord.com/users/194488028863922176'}
