# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Projects                     ', folder: 'pages', file: 'projects.html'}
- {name: 'CVEs', folder: 'pages', file: 'cves.html'}
- {name: 'Resume', folder: 'pages', file: 'resume.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/kyle-timmermans/'}
- {icon: 'envelope', link: 'mailto:kyle@kyles.world'}
- {icon: 'github', link: 'https://github.com/kyletimmermans'}
- {icon: 'twitter', link: 'https://twitter.com/kyletimmermans'}
- {icon: 'instagram', link: 'https://instagram.com/kyle_timmermans'}

# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
